products/urls.py
from django.urls import path
from . import views

from products.views import catalog, index, basket_add, basket_remove
app_name = 'products'

urlpatterns = [
    # path('index', views.index, name='Index'),
    # path('catalog', views.catalog, name='Catalog'),

    path('catalog/', catalog, name='catalog'),
    path('index/', index, name='index'),
    path('category/<int:category_id>', catalog, name='category'),
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove')

]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),


               ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import login, registration, profile, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),

]

products/models.py
from django.db import models
from django.views.generic.detail import DetailView
from users.models import User

class ProductCategory(models.Model):
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=256)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_img')
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f' Продукт: {self.name} | Категория: {self.category.name}'


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Корзина для {self.user.email} | Продукт: {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity





products/views.py
from django.shortcuts import render, HttpResponseRedirect
from products.models import ProductCategory, Product, Basket
from users.models import User

def index(request):
    context = {
        'title': 'Index',

    }
    return render(request, 'products/index.html', context)

def catalog(request, category_id=None):
    products = Product.objects.filter(category_id=category_id) if category_id else Product.objects.all()

    context = {
        'title': 'Catalog',
        'products': products,
        'categories': ProductCategory.objects.all(),
    }

    return render(request, 'products/catalog.html', context)


def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])



products/templates/products/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


  </head>
  <body>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous">
    </script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous">


<!--Navbar Menu-->

    <nav class="navbar navbar-expand-lg " style="background-color: #D2B48C;">
        <div class="container">
            <a href="{% url 'products:index' %}" class="navbar-brand"><h1 class="display-5"> Nut-shop </h1></a>

            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse" data-bs-target="#navmenu" >
                    <span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <div class="dropdown">
                          <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Каталог
                          </button>
                          <ul class="dropdown-menu">
                              {% for category in categories %}
                                <a href="{% url 'products:category' category.id %}" class="dropdown-item">
                                    {{ category.name }}
                                </a>
                              {% endfor %}
                              <li><a class="dropdown-item" href="{% url 'products:catalog' %}">Каталог</a></li>
                          </ul>
                        </div>

                    {% if user.is_authenticated %}

                        <li class="nav-item">
                            <a href="{% url 'users:profile' %}" class="nav-link">Профиль</a>
                        </li>

                         {% if user.is_superuser or user.is_stuff %}
                            <li class="nav-item">
                                <a href="{% url 'admin:index' %}" class="nav-link">Админ-панель</a>
                            </li>
                        {% endif %}

                        <li class="nav-item">
                            <a href="{% url 'users:logout' %}" class="nav-link">Выйти</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a href="{% url 'users:login' %}" class="nav-link"> Войти  </a>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

  <div class="card text-center " style="background-color: #D2B48C;" >
        <div class="card-footer sticky-bottom text-muted">
            Nut-Shop
        </div>
  </div>

  </body>
</html>


products/templates/products/baskets.html
{% load static %}

<script src="{% static 'products/vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

{% if baskets %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина <span class="badge badge-secondary badge-pill">{{ baskets.total_quantity }}</span>
    </h4>
    {% for basket in baskets %}
         <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ basket.product.name }}</h5>
                        <p class="card-text">{{ basket.product.description }}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item bg-light">
                            <div class="row text-center">
                                <div class="col-lg-4">
                                    <input name="basketID" type="number" class="form-control"
                                           value="{{ basket.quantity }}" min="0">
                                </div>
                                <div class="col-lg-4">{{ basket.sum }} руб.</div>

                                <div class="col-lg-4">
                                    <a href="{% url 'products:basket_remove' basket.id %}">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </div>
                            </div>

                        </li>
                    </ul>
                </div>
    {% endfor %}
    <div class="card mb-3">
                    <div class="card-footer">
                        <p class="float-left">Итого</p>
                        <h4 class="float-right">{{ baskets.total_sum }} руб.</h4>
                    </div>
                </div>
    <a class="btn btn-success btn-lg float-right" href="../orders/order-create.html">
        Оформить заказ
    </a>

{% else %}
    <h4 class="mt-3 mb-3 text-center">
        Корзина пуста
    </h4>
{% endif %}

products/templates/products/catalog.html
{% extends 'products/base.html'%}
{% load static %}

<title>{{ title }}</title>

{% block content %}

<!-- Boxes -->

<section>
    <div class="container p-5">
        <div class="row row-cols-1 row-cols-md-3 g-4 text-center">
            {% for product in products %}
              <div class="col">
                <div class="card h-100">
                  <img src="{{ product.image.url }}" class="card-img-top" alt="#">
                  <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.price }}</p>
                      <a href="{% url 'products:basket_add' product.id %}" class="btn btn-primary">В корзину</a>
                  </div>
                </div>
              </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

products/templates/products/index.html
{% extends 'products/base.html'%}
{% load static %}

<title>{{ title }}</title>

{% block content %}

<!-- Showcase -->

<section class="bg-light dark p-5 text-center">
    <div class="container">
        <div class="d-sm-flex ">
            <div>
                <p class="lead"> Сайт является итоговым проектом ученицы онлайн школы Бруноям - Царьковой Полины</p>

                <a href="{% url 'products:catalog' %}"><button type="button"  class="btn btn-primary" disabled>Перейти в каталог</button></a>
            </div>
            <img class="img-fluid w-50 d-none d-sm-block" src="{% static 'products/img/pngwing.com.png' %}">
        </div>
    </div>
</section>


{% endblock %}
